import 'package:flutter_test/flutter_test.dart';
import 'package:roy_casual_kit/core/utils/dependency_sbom.dart';

const _sampleLock = '''
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  get:
    dependency: "direct main"
    description:
      name: get
      sha256: "abc123"
      url: "https://pub.dev"
    source: hosted
    version: "4.7.3"
  flutter_lints:
    dependency: "direct dev"
    description:
      name: flutter_lints
      sha256: "def456"
      url: "https://pub.dev"
    source: hosted
    version: "6.0.0"
  async:
    dependency: transitive
    description:
      name: async
      sha256: "ghi789"
      url: "https://pub.dev"
    source: hosted
    version: "2.13.1"
  flutter:
    dependency: "direct main"
    description: flutter
    source: sdk
    version: "0.0.0"
sdks:
  dart: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"
''';

void main() {
  group('parsePubspecLock', () {
    test('parse đủ 4 package, đúng type/source/version', () {
      final entries = parsePubspecLock(_sampleLock);
      expect(entries, hasLength(4));

      final get = entries.firstWhere((e) => e.name == 'get');
      expect(get.type, DependencyType.directMain);
      expect(get.source, DependencySource.hosted);
      expect(get.version, '4.7.3');

      final lints = entries.firstWhere((e) => e.name == 'flutter_lints');
      expect(lints.type, DependencyType.directDev);

      final async_ = entries.firstWhere((e) => e.name == 'async');
      expect(async_.type, DependencyType.transitive);

      final flutter = entries.firstWhere((e) => e.name == 'flutter');
      expect(flutter.source, DependencySource.sdk);
    });

    test('kết quả LUÔN sort theo tên -> reproducible bất kể thứ tự trong file', () {
      final entries = parsePubspecLock(_sampleLock);
      final names = entries.map((e) => e.name).toList();
      final sorted = [...names]..sort();
      expect(names, sorted);
    });

    test('sdks: section ở cuối không bị hiểu nhầm thành package mới', () {
      final entries = parsePubspecLock(_sampleLock);
      expect(entries.map((e) => e.name), isNot(contains('sdks')));
      // "dart" và "flutter" trong sdks: là dòng có giá trị inline, không
      // phải top-level key rỗng — không tạo entry giả thứ 2 cho "flutter".
      expect(entries.where((e) => e.name == 'flutter'), hasLength(1));
    });

    test('input rỗng/rác -> trả về list rỗng, không throw', () {
      expect(parsePubspecLock(''), isEmpty);
      expect(parsePubspecLock('garbage\nnot a lock file\n'), isEmpty);
    });
  });

  group('SbomDocument: reproducible JSON', () {
    test('toJson() có đủ field, entries theo đúng thứ tự đã sort', () {
      final entries = parsePubspecLock(_sampleLock);
      final doc = SbomDocument(
        packageName: 'roy_casual_kit',
        packageVersion: '0.2.0',
        generatedAtMs: 1000,
        entries: entries,
      );
      final json = doc.toJson();
      expect(json['packageName'], 'roy_casual_kit');
      expect(json['generatedAtMs'], 1000);
      final jsonEntries = json['entries'] as List;
      expect(jsonEntries, hasLength(4));
      expect((jsonEntries.first as Map)['name'], 'async');
    });

    test('2 lần build từ CÙNG lock file -> JSON giống hệt nhau (reproducible)', () {
      final entries1 = parsePubspecLock(_sampleLock);
      final entries2 = parsePubspecLock(_sampleLock);
      final doc1 = SbomDocument(packageName: 'x', packageVersion: '1', generatedAtMs: 1, entries: entries1);
      final doc2 = SbomDocument(packageName: 'x', packageVersion: '1', generatedAtMs: 1, entries: entries2);
      expect(doc1.toJson(), doc2.toJson());
    });
  });

  group('classifyLicenseText', () {
    test('MIT -> permissive', () {
      expect(classifyLicenseText('MIT License\n\nCopyright (c) 2024 X'), LicenseCategory.permissive);
    });

    test('Apache -> permissive', () {
      expect(classifyLicenseText('Apache License\nVersion 2.0'), LicenseCategory.permissive);
    });

    test('GPL -> copyleft', () {
      expect(
        classifyLicenseText('GNU GENERAL PUBLIC LICENSE\nVersion 3'),
        LicenseCategory.copyleft,
      );
    });

    test('LGPL -> copyleft (không bị nhầm thành permissive dù có chữ "GPL")', () {
      expect(
        classifyLicenseText('GNU LESSER GENERAL PUBLIC LICENSE'),
        LicenseCategory.copyleft,
      );
    });

    test(
      'PHÁT HIỆN THẬT: BSD boilerplate của dart.dev/Google (không có chữ "BSD") '
      '-> vẫn nhận đúng permissive, không báo nhầm unknown',
      () {
        // Text thật lấy từ package `meta`/`path`/`collection`... trong
        // pub cache — verify trước khi viết test, không phải suy đoán.
        const realDartTeamLicense = '''
Copyright 2016, the Dart project authors.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:
''';
        expect(classifyLicenseText(realDartTeamLicense), LicenseCategory.permissive);
      },
    );

    test(
      'PHÁT HIỆN THẬT: MIT body text không có tiêu đề "MIT License" (vd package uuid) '
      '-> vẫn nhận đúng permissive',
      () {
        const realUuidLicense =
            'Copyright (c) 2021 Yulian Kuncheff\n\n'
            'Permission is hereby granted, free of charge, to any person '
            'obtaining a copy of this software...';
        expect(classifyLicenseText(realUuidLicense), LicenseCategory.permissive);
      },
    );

    test(
      'MPL-2.0 (vd package dbus) -> unknown (không permissive cũng không GPL-family, cần review tay)',
      () {
        const realDbusLicense = 'Mozilla Public License Version 2.0\n==================================\n';
        expect(classifyLicenseText(realDbusLicense), LicenseCategory.unknown);
      },
    );

    test('null/rỗng/không nhận diện được -> unknown', () {
      expect(classifyLicenseText(null), LicenseCategory.unknown);
      expect(classifyLicenseText(''), LicenseCategory.unknown);
      expect(classifyLicenseText('some random proprietary text'), LicenseCategory.unknown);
    });
  });

  group('auditDependencies: license', () {
    final entries = [
      const DependencyEntry(name: 'good_pkg', version: '1.0.0', type: DependencyType.directMain, source: DependencySource.hosted),
      const DependencyEntry(name: 'gpl_pkg', version: '1.0.0', type: DependencyType.transitive, source: DependencySource.hosted),
      const DependencyEntry(name: 'no_license_pkg', version: '1.0.0', type: DependencyType.transitive, source: DependencySource.hosted),
      const DependencyEntry(name: 'flutter', version: '0.0.0', type: DependencyType.directMain, source: DependencySource.sdk),
    ];
    final licenseByPackage = {
      'good_pkg': LicenseCategory.permissive,
      'gpl_pkg': LicenseCategory.copyleft,
    };

    test('package permissive -> không issue', () {
      final issues = auditDependencies(entries: entries, licenseByPackage: licenseByPackage, nowMs: 0);
      expect(issues.where((i) => i.package == 'good_pkg'), isEmpty);
    });

    test('package copyleft -> issue severity high', () {
      final issues = auditDependencies(entries: entries, licenseByPackage: licenseByPackage, nowMs: 0);
      final issue = issues.singleWhere((i) => i.package == 'gpl_pkg');
      expect(issue.kind, SbomIssueKind.copyleftLicense);
      expect(issue.severity, AdvisorySeverity.high);
    });

    test('package không rõ license -> issue severity low', () {
      final issues = auditDependencies(entries: entries, licenseByPackage: licenseByPackage, nowMs: 0);
      final issue = issues.singleWhere((i) => i.package == 'no_license_pkg');
      expect(issue.kind, SbomIssueKind.unknownLicense);
      expect(issue.severity, AdvisorySeverity.low);
    });

    test('package source=sdk (vd flutter) -> không kiểm tra license, không issue', () {
      final issues = auditDependencies(entries: entries, licenseByPackage: licenseByPackage, nowMs: 0);
      expect(issues.where((i) => i.package == 'flutter'), isEmpty);
    });
  });

  group('auditDependencies: vulnerability (cross-check, không tự scan)', () {
    final entries = [
      const DependencyEntry(name: 'vuln_pkg', version: '1.2.3', type: DependencyType.transitive, source: DependencySource.hosted),
    ];

    test('advisory khớp đúng package+version -> báo issue', () {
      final issues = auditDependencies(
        entries: entries,
        licenseByPackage: const {'vuln_pkg': LicenseCategory.permissive},
        nowMs: 0,
        advisories: const [
          VulnerabilityAdvisory(
            package: 'vuln_pkg',
            version: '1.2.3',
            severity: AdvisorySeverity.critical,
            description: 'RCE trong parser',
          ),
        ],
      );
      final vuln = issues.singleWhere((i) => i.kind == SbomIssueKind.vulnerability);
      expect(vuln.severity, AdvisorySeverity.critical);
      expect(vuln.detail, contains('RCE'));
    });

    test('advisory KHÁC version đang dùng -> không báo (đã fix ở version khác)', () {
      final issues = auditDependencies(
        entries: entries,
        licenseByPackage: const {'vuln_pkg': LicenseCategory.permissive},
        nowMs: 0,
        advisories: const [
          VulnerabilityAdvisory(
            package: 'vuln_pkg',
            version: '1.0.0',
            severity: AdvisorySeverity.critical,
            description: 'đã fix ở 1.2.3',
          ),
        ],
      );
      expect(issues.where((i) => i.kind == SbomIssueKind.vulnerability), isEmpty);
    });
  });

  group('auditDependencies: unpinned constraint', () {
    test('package trong unpinnedPackages -> báo issue medium', () {
      final issues = auditDependencies(
        entries: const [],
        licenseByPackage: const {},
        nowMs: 0,
        unpinnedPackages: const {'wild_pkg'},
      );
      final issue = issues.singleWhere((i) => i.kind == SbomIssueKind.unpinnedConstraint);
      expect(issue.package, 'wild_pkg');
      expect(issue.severity, AdvisorySeverity.medium);
    });
  });

  group('PHÁT HIỆN THẬT: suppression hết hạn tự động hết hiệu lực', () {
    final entries = [
      const DependencyEntry(name: 'no_license_pkg', version: '1.0.0', type: DependencyType.transitive, source: DependencySource.hosted),
    ];

    test('suppression còn hạn -> issue bị ẩn', () {
      final issues = auditDependencies(
        entries: entries,
        licenseByPackage: const {},
        nowMs: 1000,
        suppressions: const [
          SbomSuppression(
            package: 'no_license_pkg',
            kind: SbomIssueKind.unknownLicense,
            reason: 'đã review tay, an toàn',
            owner: 'roy',
            expiresAtMs: 2000,
          ),
        ],
      );
      expect(issues, isEmpty);
    });

    test('suppression đã hết hạn -> issue XUẤT HIỆN LẠI, không bị ẩn mãi mãi', () {
      final issues = auditDependencies(
        entries: entries,
        licenseByPackage: const {},
        nowMs: 5000,
        suppressions: const [
          SbomSuppression(
            package: 'no_license_pkg',
            kind: SbomIssueKind.unknownLicense,
            reason: 'đã review tay, an toàn',
            owner: 'roy',
            expiresAtMs: 2000,
          ),
        ],
      );
      expect(issues, hasLength(1));
      expect(issues.single.package, 'no_license_pkg');
    });

    test('suppression đúng package nhưng sai kind -> không áp dụng, issue vẫn báo', () {
      final issues = auditDependencies(
        entries: entries,
        licenseByPackage: const {},
        nowMs: 1000,
        suppressions: const [
          SbomSuppression(
            package: 'no_license_pkg',
            kind: SbomIssueKind.vulnerability,
            reason: 'không liên quan',
            owner: 'roy',
            expiresAtMs: 9999,
          ),
        ],
      );
      expect(issues, hasLength(1));
    });
  });
}
